### PR TITLE
Fix cmake paths generator

### PR DESCRIPTION
**Pull request by uilianries**
Pulling @vogoltsov changes to fix https://github.com/conan-community/community/issues/221

fixes https://github.com/conan-community/community/issues/221

### CODE REVIEW

**Comment by SSE4** [comment]
seems like patch doesn't apply:
```
ARN: 0002-fix-cmake-find-paho-mqtt-c-static.patch: extra lines for hunk no.1 at 16 for target b'b/cmake/FindPahoMqttC.cmake'
WARN: 0002-fix-cmake-find-paho-mqtt-c-static.patch: warning: finished with errors, some hunks may be invalid
paho-cpp/1.0.1@conan/stable: ERROR: Package 'abc7a1a01cc8e580c9fc74e930ebd804bcc6358e' build failed
```

**Comment by uilianries** [comment]
Ops! some of my commits are missing.

**Comment by uilianries** [comment]
I just pushed a fix, let's wait for CI result

**Comment by vogoltsov** [comment]
Ok, I have corrected the fix in my branch at https://github.com/vogoltsov/conan-paho-cpp/tree/fix-cmake-paths-generator:
- fixed issue with the patch (my bad, haven't updated it with the latest
- fixed error in `conanfile.py` when dependency properties were set in `config_options()` (according to https://docs.conan.io/en/latest/mastering/conditional.html they should be set in `configure()`)
- fixed typo in @uilianries 's commit (`CXX_STANDARD REQUIRED` -> `CXX_STANDARD_REQUIRED`, etc.) which prevented tests from building

I still have issue with 32-bit builds or builds with `compiler.libcxx=libstdc++` not compiling - seems there is some error in CMakeLists.txt in test_package. x86_64 with `libstdc++11` seems to be working fine.
Could you please update the testing branch and help me with this issue?

**Comment by uilianries** [comment]
@vogoltsov Done! I just merged your branch.

**Comment by SSE4** [comment]
now build fails:
```
/home/conan/.conan/data/paho-cpp/1.0.1/conan/stable/package/abc7a1a01cc8e580c9fc74e930ebd804bcc6358e/lib/libpaho-mqttpp3.so.1.0.1: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
```

**Comment by vogoltsov** [comment]
@uilianries @SSE4 So I have located the problem: when using `cmake` generator, compiler and linker flags (such as stdc++ version and arch) are set by conan. But when using `cmake_paths`, these values should be (in theory) defined by the developer, or are automatically guessed by CMake itself.
As we don't want to create `CMakeLists.txt` for every possible combination of `compiler.libcxx`, `arch`, etc., I am using a stripped-down version of `conan_basic_setup()` which does not modify include and library paths:
```cmake
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_set_libcxx()
conan_set_flags("")
conan_set_flags("_RELEASE")
conan_set_flags("_DEBUG")
```

I have tested these with `conan/gcc8` and `conan/gcc5` using the following command:
```bash
docker run -it --rm -v `pwd`:`pwd` -w `pwd` -e CONAN_GCC_VERSIONS=8 -e CONAN_USERNAME=`id -nu` conanio/gcc8 python build.py
```
I currently have no way of checking a Windows build, so fingers crossed...

I have amended (for a bit cleaner history) and **signed** commits on my branch. Please rebase if possible.

**Comment by vogoltsov** [comment]
I have just checked and fixed testing issues on Windows platforms with VS2019, everything's working fine.

**Comment by SSE4** [comment]
@uilianries could you possibly take a look at new changes?

**Comment by uilianries** [comment]
When using Conan CMake path, Conan only generates a cmake file with paths, nothing else. 
The test package used to validate cmake_paths has find_package to find all dependencies, which is not correct. When find_package works with cmake_paths, it's because conanbuildinfo.cmake helped you to find all dependencies. However, as you know CMake is limited in terms of dependency management, which means Paho C is not being solved by PahoCpp, which means you need to add CONAN_PKG:paho-c, or add manually all library names.

**Comment by vogoltsov** [comment]
@uilianries Sorry, I can’t agree on this one, I think you have confused how these generators work.

cmake_paths is used to setup system path variables so that find_package() works as if the package was indeed installed in the system.

On the other hand, conanbuildinfo.txt sets up all dependencies and variables so that no find_package() call is needed. And it doesn’t work unless you call conan_basic_setup() macro - which as you can see I am not using.
Furthermore, I have initially tested the package with cmake_paths and without conanbuildinfo.txt - it worked but not with all compiler/arch configurations - cause it lacked certain compiler/arch detection routines, which (and only these ones) I have included from conanbuildinfo.txt (instead of duplicating code or setting variables from python code).

**Comment by vogoltsov** [comment]
@uilianries more info on generators with examples: https://blog.conan.io/2018/06/11/Transparent-CMake-Integration.html

**Comment by uilianries** [comment]
It's working, I think we a good to merge now.

**Pull request merged**
